### ISSUE TITLE
Fetch and display CHANGELOG.md while selecting version of dependency as documentation

### ISSUE THREAD

**Issue by IchordeDionysos** [marius-h/flutter_enhancement_suite#27]
**Describe the use-cases of your feature**

When deciding whether to update a package now. It's useful to check what has changed since the version you have.

**Describe your solution**

It would be cool I one could fetch and display CHANGELOG.md while selecting the version of a dependency when you try to open the documentation.

On MacOS:
1. Move cursor to version of dependency

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1[cursor here].1
``` 
2. Press _F1_
3. Show a dropdown with the CHANGELOG.md, just like you display the README.md for the documentation of a package
