### ISSUE TITLE
Support maps for lint rules in analysis_options.yaml

### ISSUE THREAD

**Issue by KaBankz** [marius-h/flutter_enhancement_suite#65]
If you use a linter package like [pedantic](https://pub.dev/packages/pedantic) or [lint](https://pub.dev/packages/lint) you cannot override rules using the "lint rules editor" because it only supports adding and removing rules as a list item, but to override rules you must define rules as a map as stated here:
https://dart.dev/guides/language/analysis-options#disabling-individual-rules

**Describe your solution**
Since yaml restrictions will not let you mix list syntax and key value syntax, I suggest making maps default
So instead of
```yaml
linter:
  rules:
    - prefer_single_quotes
```

it would be
```yaml
linter:
  rules:
    prefer_single_quotes: true
```
and to disable default rules
```yaml
linter:
  rules:
    lines_longer_than_80_chars: false
```
